name = "Simon Foster"
  location = "North England"
  about = "/about"
  bio = ".NET developer | Azure & DevOps specialist | 18+ years building scalable solutions"

[social]
  email = "funkysi1701@gmail.com"
  facebook = "funkysi1701"
  twitter = "funkysi1701"
  mastodon = "@funkysi1701"
  bluesky = "funkysi1701.com"
  github = "funkysi1701"
  linkedin = "in/funkysi1701/"
  avatar = "images/profile.jpg"


