name = "Simon Foster"
  location = "North England"
  about = "/about"
  bio = "I am Simon Foster (aka funkysi1701) a developer sharing 18+ years of experience in .NET, Azure, and DevOps. I write about cloud architecture, CI/CD pipelines, and building scalable applications."

[social]
  email = "funkysi1701@gmail.com"
  avatar = "images/profile.jpg"


