baseURL = 'https://blog-dev.funkysi1701.com/'
title = "Development Version of Funky Si's Blog"

[params]
  cdnImagePrefix = ""
  googleAdsense = ""

[params.search]
  analyticsUrl = "https://azurefunction-d4bkcjdahseefphm.uksouth-01.azurewebsites.net/api/SaveToDb"
